import { z } from 'zod';

/**
 * Environment variable validation schema using Zod.
 * This ensures type-safe access to environment variables at runtime.
 */
const envSchema = z.object({
  // Convex (auto-generated by `npx convex dev`)
  CONVEX_DEPLOYMENT: z.string().optional(),
  NEXT_PUBLIC_CONVEX_URL: z
    .string()
    .url({ message: 'NEXT_PUBLIC_CONVEX_URL must be a valid URL' }),

  // OAuth - Google (set in Convex dashboard)
  AUTH_GOOGLE_ID: z.string().optional(),
  AUTH_GOOGLE_SECRET: z.string().optional(),

  // OAuth - GitHub (set in Convex dashboard)
  AUTH_GITHUB_ID: z.string().optional(),
  AUTH_GITHUB_SECRET: z.string().optional(),
});

/**
 * Inferred type from the environment schema.
 * Use this type when you need to reference environment variables in TypeScript.
 */
export type Env = z.infer<typeof envSchema>;

/**
 * Validates environment variables and returns a typed object.
 * Validates both server and client-side public variables.
 */
function validateEnv(): Env {
  const result = envSchema.safeParse({
    CONVEX_DEPLOYMENT: process.env.CONVEX_DEPLOYMENT,
    NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,
    AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
    AUTH_GITHUB_ID: process.env.AUTH_GITHUB_ID,
    AUTH_GITHUB_SECRET: process.env.AUTH_GITHUB_SECRET,
  });

  if (!result.success) {
    const errors = result.error.flatten().fieldErrors;
    const errorMessages = Object.entries(errors)
      .map(([field, messages]) => `  - ${field}: ${messages?.join(', ')}`)
      .join('\n');

    // Only throw in production or if it's a critical error
    if (process.env.NODE_ENV === 'production') {
      throw new Error(
        `Environment validation failed:\n${errorMessages}\n\n` +
          'Please check your environment variables and ensure all required variables are set.'
      );
    } else {
      console.warn(
        `Environment validation warning:\n${errorMessages}\n\n` +
          'Some environment variables are missing. Run `npx convex dev` to set up Convex.'
      );
      // Return partial env for development
      return result.data as Env;
    }
  }

  return result.data;
}

/**
 * Validated and typed environment variables.
 * Access environment variables through this object for type safety.
 *
 * @example
 * import { env } from '@/lib/env';
 *
 * // Type-safe access
 * const convexUrl = env.NEXT_PUBLIC_CONVEX_URL;
 */
export const env = validateEnv();
