import { existsSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import type { HarnessRun, VariantState } from "./harness-state";

function formatDuration(ms: number): string {
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  if (minutes > 0) {
    return `${minutes}m ${remainingSeconds}s`;
  }
  return `${seconds}s`;
}

function getStatusEmoji(status: string): string {
  switch (status) {
    case "completed":
      return "✅";
    case "failed":
      return "❌";
    case "timeout":
      return "⏱️";
    case "running":
      return "🔄";
    case "pending":
      return "⏳";
    default:
      return "❓";
  }
}

function calculateDuration(variant: VariantState): number {
  if (!variant.startedAt) return 0;
  const start = new Date(variant.startedAt).getTime();
  const end = variant.completedAt 
    ? new Date(variant.completedAt).getTime() 
    : Date.now();
  return end - start;
}

export function generateHarnessReport(rootDir: string, run: HarnessRun): string {
  const lines: string[] = [
    `# POC Harness Report`,
    "",
    `**Run ID:** ${run.id}`,
    `**Goal:** ${run.goal}`,
    `**Base Branch:** ${run.baseBranch}`,
    `**Created:** ${run.createdAt}`,
    run.completedAt ? `**Completed:** ${run.completedAt}` : `**Status:** In Progress`,
    run.prdHash ? `**PRD Hash:** ${run.prdHash}` : "",
    "",
    "---",
    "",
    "## Variant Summary",
    "",
    "| Variant | Status | Duration | Exit Code |",
    "|---------|--------|----------|-----------|",
  ];

  for (const variant of run.variants) {
    const emoji = getStatusEmoji(variant.status);
    const duration = formatDuration(calculateDuration(variant));
    const exitCode = variant.exitCode !== undefined ? variant.exitCode.toString() : "-";
    const selected = run.selectedVariant === variant.id ? " 🏆" : "";
    lines.push(`| ${variant.name}${selected} | ${emoji} ${variant.status} | ${duration} | ${exitCode} |`);
  }

  lines.push("");

  // Detailed sections for each variant
  for (const variant of run.variants) {
    lines.push(`## ${variant.name}`);
    lines.push("");
    lines.push(`**ID:** ${variant.id}`);
    lines.push(`**Worktree:** ${variant.worktreePath}`);
    lines.push(`**Branch:** ${variant.branch}`);
    lines.push(`**Status:** ${getStatusEmoji(variant.status)} ${variant.status}`);
    
    if (variant.error) {
      lines.push(`**Error:** ${variant.error}`);
    }

    if (variant.logPath) {
      lines.push(`**Log:** [${variant.logPath}](${variant.logPath})`);
    }

    lines.push("");

    // Include POC summary if available
    if (variant.summary) {
      lines.push("### POC Summary");
      lines.push("");
      lines.push(variant.summary);
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  // Recommendations
  lines.push("## Recommendations");
  lines.push("");

  const completed = run.variants.filter((v) => v.status === "completed");
  const failed = run.variants.filter((v) => v.status === "failed" || v.status === "timeout");

  if (completed.length === 0) {
    lines.push("⚠️ No variants completed successfully. Review error logs and retry.");
  } else if (completed.length === 1) {
    lines.push(`Only **${completed[0].name}** completed successfully.`);
    lines.push("");
    lines.push(`To select this variant: \`ccplate harness pick ${completed[0].id}\``);
  } else {
    lines.push(`${completed.length} variants completed. Review each approach and select the best one.`);
    lines.push("");
    lines.push("### Selection Commands");
    lines.push("");
    for (const v of completed) {
      lines.push(`- \`ccplate harness pick ${v.id}\` - Select ${v.name}`);
    }
  }

  if (failed.length > 0) {
    lines.push("");
    lines.push(`### Failed Variants (${failed.length})`);
    lines.push("");
    for (const v of failed) {
      lines.push(`- **${v.name}**: ${v.error || v.status}`);
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(`*Generated by CCPLATE Harness on ${new Date().toISOString()}*`);

  return lines.join("\n");
}

export function saveHarnessReport(rootDir: string, run: HarnessRun): string {
  const harnessDir = join(rootDir, "memory", "harness");
  if (!existsSync(harnessDir)) {
    mkdirSync(harnessDir, { recursive: true });
  }

  const reportPath = join(harnessDir, "report.md");
  const report = generateHarnessReport(rootDir, run);
  writeFileSync(reportPath, report);

  // Also save run-specific report
  const runReportPath = join(harnessDir, `report-${run.id}.md`);
  writeFileSync(runReportPath, report);

  return reportPath;
}

export function printVariantComparison(run: HarnessRun): void {
  console.log("\n" + "═".repeat(60));
  console.log("  📊 POC Harness Results");
  console.log("═".repeat(60) + "\n");

  console.log(`Goal: ${run.goal}\n`);

  const colWidths = { name: 20, status: 12, duration: 10, code: 6 };
  const header = [
    "Variant".padEnd(colWidths.name),
    "Status".padEnd(colWidths.status),
    "Duration".padEnd(colWidths.duration),
    "Exit",
  ].join(" | ");

  console.log(header);
  console.log("-".repeat(header.length));

  for (const variant of run.variants) {
    const emoji = getStatusEmoji(variant.status);
    const duration = formatDuration(calculateDuration(variant));
    const exitCode = variant.exitCode !== undefined ? variant.exitCode.toString() : "-";
    const selected = run.selectedVariant === variant.id ? " 🏆" : "";

    const row = [
      (variant.name + selected).padEnd(colWidths.name),
      `${emoji} ${variant.status}`.padEnd(colWidths.status),
      duration.padEnd(colWidths.duration),
      exitCode,
    ].join(" | ");

    console.log(row);
  }

  console.log();
}
